## Project Part 1

###Team members:
Arshiya Sawhney: as5476

Ijaz Ahmed Khan: ik2557

In [ ]:
import pandas as pd
import requests

First, trying to load in dataset using the API

In [ ]:
api_url = "https://data.elexon.co.uk/bmrs/api/v1/generation/actual/per-type?from=2024-01-01&to=2025-02-06&settlementPeriodFrom=1&settlementPeriodTo=48&format=json"

In [ ]:
generation_by_fuel = requests.get(api_url)
df1 = pd.DataFrame(generation_by_fuel)
df1.head()
## need to check how to clean the dataset

                                                   0
0  b'{"type":"https://tools.ietf.org/html/rfc9110...
1  b'ors":{"":["The date range between From and T...
2                        b'19-89bc1b340e616204-00"}'

Since we are currently running into issues with the API, we have loaded in the dataset in as a csv for now.

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving bac410d3-8a3e-4c8d-9aad-617038c2e8f6.csv to bac410d3-8a3e-4c8d-9aad-617038c2e8f6.csv

In [ ]:
data = pd.read_csv("bac410d3-8a3e-4c8d-9aad-617038c2e8f6.csv")
data.head()

,Dataset,PublishTime,StartTime,SettlementDate,SettlementPeriod,FuelType,Generation
0,FUELHH,2025-02-06T05:30:00Z,2025-02-06T05:00:00Z,2025-02-06,11,BIOMASS,3044
1,FUELHH,2025-02-06T05:30:00Z,2025-02-06T05:00:00Z,2025-02-06,11,CCGT,16799
2,FUELHH,2025-02-06T05:30:00Z,2025-02-06T05:00:00Z,2025-02-06,11,COAL,0
3,FUELHH,2025-02-06T05:30:00Z,2025-02-06T05:00:00Z,2025-02-06,11,INTELEC,-302
4,FUELHH,2025-02-06T05:30:00Z,2025-02-06T05:00:00Z,2025-02-06,11,INTEW,-26